/* =============================================================
   CV CONTENT — generated by the visual editor (editor.html).
   You can still edit this file by hand.
   - Bilingual value:  { "en": "...", "pl": "..." }
   - Same in both langs: a plain "string".
   ============================================================= */

const CV = {
  "meta": {
    "defaultLang": "en",
    "title": "Dawid Ciupka — DevOps / Platform Engineer",
    "description": "Dawid Ciupka — DevOps / Platform Engineer. Kubernetes, Docker, CI/CD, Python, MQTT, IoT."
  },
  "name": "Dawid Ciupka",
  "role": "DevOps / Platform Engineer",
  "tagline": {
    "en": "I build systems, automate everything, and make infrastructure actually work.",
    "pl": "Buduję systemy, automatyzuję wszystko i sprawiam, że infrastruktura faktycznie działa."
  },
  "linkedin": {
    "vanity": "dawid-ciupka",
    "url": "https://www.linkedin.com/in/dawid-ciupka"
  },
  "contact": {
    "portfolio": "https://dciupka.github.io/cv/",
    "portfolioLabel": {
      "en": "Interactive Portfolio & Projects",
      "pl": "Interaktywne Portfolio i Projekty"
    },
    "github": "https://github.com/dciupka",
    "email": "dawidciupka@gmail.com",
    "phone": "+48794219389",
    "phoneDisplay": "+48 794 219 389",
    "location": {
      "en": "Wrocław, Poland",
      "pl": "Wrocław, Polska"
    }
  },
  "sections": [
    {
      "type": "about",
      "heading": {
        "en": "About",
        "pl": "O mnie"
      },
      "paragraphs": [
        {
          "en": "DevOps / Platform Engineer with a background in Industrial Automation. I build and operate real infrastructure — self-hosted Kubernetes clusters, CI/CD pipelines, IoT integrations, and embedded systems. I work at the intersection of systems engineering and software, bridging the gap between hardware and cloud-native tooling.",
          "pl": "Inżynier DevOps / Platform z doświadczeniem w automatyce przemysłowej. Buduję i utrzymuję realną infrastrukturę — własne klastry Kubernetes, pipeline'y CI/CD, integracje IoT i systemy wbudowane. Działam na styku inżynierii systemowej i oprogramowania, łącząc sprzęt z narzędziami chmurowymi."
        },
        {
          "en": "Previously a PLC programmer (Allen Bradley, Siemens) and mechanical designer (Autodesk Inventor), now focused on Kubernetes, Docker, Python, MQTT and making infrastructure actually work.",
          "pl": "Wcześniej programista PLC (Allen Bradley, Siemens) i konstruktor mechaniczny (Autodesk Inventor), teraz skupiony na Kubernetes, Docker, Python, MQTT i budowaniu infrastruktury, która po prostu działa."
        }
      ],
      "tags": [
        {
          "en": "Automate first",
          "pl": "Najpierw automatyzacja"
        },
        {
          "en": "Build real things",
          "pl": "Buduję realne rzeczy"
        },
        {
          "en": "Hands-on engineering",
          "pl": "Praktyczna inżynieria"
        }
      ]
    },
    {
      "type": "projects",
      "heading": {
        "en": "Professional Projects",
        "pl": "Projekty Zawodowe"
      },
      "items": [
        {
          "title": "Smart Building Platform",
          "rows": [
            {
              "label": {
                "en": "Context:",
                "pl": "Kontekst:"
              },
              "text": {
                "en": "Client from the building management sector.",
                "pl": "Klient z sektora zarządzania budynkami."
              }
            },
            {
              "label": {
                "en": "Scope:",
                "pl": "Zakres:"
              },
              "text": {
                "en": "Deployment and configuration on a self-hosted Kubernetes cluster managed via Rancher. Full platform architecture design, TLS certificate management, and enterprise authentication integration.",
                "pl": "Wdrożenie i konfiguracja na własnym klastrze Kubernetes zarządzanym przez Rancher. Projektowanie architektury platformy, zarządzanie certyfikatami TLS oraz integracja uwierzytelniania korporacyjnego."
              }
            },
            {
              "label": {
                "en": "Stack:",
                "pl": "Stack:"
              },
              "text": "Kubernetes · Rancher · Docker · SAML"
            },
            {
              "label": {
                "en": "Result:",
                "pl": "Wynik:"
              },
              "text": {
                "en": "Production-ready smart building platform with secure SSO authentication and containerized deployment.",
                "pl": "Produkcyjna platforma zarządzania budynkami z bezpiecznym SSO i wdrożeniem kontenerowym."
              }
            }
          ]
        },
        {
          "title": {
            "en": "Environment Monitoring System",
            "pl": "Platforma Monitorowania Warunków dla Farmacji"
          },
          "rows": [
            {
              "label": {
                "en": "Context:",
                "pl": "Kontekst:"
              },
              "text": {
                "en": "Client from the pharmaceutical sector (confidential).",
                "pl": "Klient z sektora farmaceutycznego (poufne)."
              }
            },
            {
              "label": {
                "en": "Scope:",
                "pl": "Zakres:"
              },
              "text": {
                "en": "Architecture design and deployment of an environment monitoring platform on Kubernetes. Handled full PKI and certificate lifecycle, implemented OAuth 2.0 and SAML-based SSO for enterprise identity provider integration.",
                "pl": "Projektowanie architektury i wdrożenie platformy monitorowania warunków na Kubernetes. Zarządzanie pełnym cyklem życia PKI i certyfikatów, implementacja OAuth 2.0 oraz SSO opartego na SAML z integracją korporacyjnego dostawcy tożsamości."
              }
            },
            {
              "label": {
                "en": "Stack:",
                "pl": "Stack:"
              },
              "text": "Kubernetes · Rancher · OAuth 2.0 · SAML"
            },
            {
              "label": {
                "en": "Result:",
                "pl": "Wynik:"
              },
              "text": {
                "en": "Secure, compliant monitoring platform integrated with client's enterprise identity infrastructure.",
                "pl": "Bezpieczna, zgodna z wymogami platforma monitorowania zintegrowana z korporacyjną infrastrukturą tożsamości klienta."
              }
            }
          ]
        }
      ]
    },
    {
      "type": "projects",
      "heading": {
        "en": "Personal Projects",
        "pl": "Projekty Prywatne"
      },
      "items": [
        {
          "title": "Kubernetes Cluster (Rancher & HA)",
          "rows": [
            {
              "label": {
                "en": "Problem:",
                "pl": "Problem:"
              },
              "text": {
                "en": "Need for a production-grade, highly available local environment to orchestrate microservices and IoT workloads without recurring cloud costs.",
                "pl": "Potrzeba produkcyjnej klasy, wysokodostępnego środowiska lokalnego do orkiestracji mikroserwisów i zadań IoT bez stałych kosztów chmurowych."
              }
            },
            {
              "label": {
                "en": "Solution:",
                "pl": "Rozwiązanie:"
              },
              "text": {
                "en": "Designed and deployed a multi-node K8s cluster using Rancher for management. Implemented MetalLB for Load Balancing, Longhorn for distributed block storage, and Traefik as Ingress Controller. Integrated Prometheus and Grafana for full-stack observability.",
                "pl": "Zaprojektowałem i wdrożyłem wielowęzłowy klaster K8s zarządzany przez Rancher. Zaimplementowałem MetalLB jako Load Balancer, Longhorn dla rozproszonego storage'u oraz Traefik jako Ingress Controller. Zintegrowałem system z Prometheus i Grafana dla pełnej obserwowalności."
              }
            },
            {
              "label": {
                "en": "Stack:",
                "pl": "Stack:"
              },
              "text": "Kubernetes · Rancher · Longhorn · MetalLB · Prometheus · Grafana · Docker"
            },
            {
              "label": {
                "en": "Grafana:",
                "pl": "Grafana:"
              },
              "text": "https://status.appevil.pl/"
            }
          ]
        },
        {
          "title": "Home Lab — Proxmox + GitOps (Flux)",
          "rows": [
            {
              "label": {
                "en": "Problem:",
                "pl": "Problem:"
              },
              "text": {
                "en": "Wanted a reproducible, fully declarative home lab — from bare Proxmox nodes to running apps — that I can rebuild from scratch without manual clicking.",
                "pl": "Powtarzalny, w pełni deklaratywny home lab — od czystych node'ów Proxmox po działające aplikacje — możliwy do odtworzenia od zera bez ręcznego klikania."
              }
            },
            {
              "label": {
                "en": "Solution:",
                "pl": "Rozwiązanie:"
              },
              "text": {
                "en": "PowerShell pipeline bootstraps a Proxmox cluster from Windows — idempotent SSH key and ssh-mesh distribution, host-key scanning, pvecm cluster creation and quorum handling with a clean reset path. On top, a Flux GitOps repo continuously reconciles the cluster from Git, with apps managed declaratively via Kustomize (web apps, Cloudflare tunnel, observability stack).",
                "pl": "Pipeline PowerShell bootstrapuje klaster Proxmox z Windowsa — idempotentna dystrybucja kluczy SSH i ssh-mesh, skanowanie host keys, tworzenie klastra pvecm i obsługa quorum z czystą ścieżką resetu. Na wierzchu repo GitOps oparte o Flux ciągle uzgadnia stan klastra z Gita, a aplikacje są zarządzane deklaratywnie przez Kustomize (aplikacje webowe, tunel Cloudflare, stack observability)."
              }
            },
            {
              "label": {
                "en": "Stack:",
                "pl": "Stack:"
              },
              "text": "Proxmox · PowerShell · Flux CD · Kustomize · Kubernetes · Git · Cloudflare Tunnel"
            },
            {
              "label": {
                "en": "Result:",
                "pl": "Wynik:"
              },
              "text": {
                "en": "A repeatable bare-metal-to-apps home lab: cluster bootstrap is automated and the running state is driven entirely from Git.",
                "pl": "Powtarzalny home lab od bare-metal po aplikacje: bootstrap klastra jest zautomatyzowany, a stan działający w całości wynika z Gita."
              }
            }
          ]
        },
        {
          "title": "LifeOS — Self-Hosted Agentic LLM Platform (in progress)",
          "rows": [
            {
              "label": {
                "en": "Problem:",
                "pl": "Problem:"
              },
              "text": {
                "en": "Wanted a private, self-hosted personal assistant for calendar, notes and reminders — driven by an LLM, without sending personal data to third-party cloud AI providers.",
                "pl": "Prywatny, self-hostowany asystent osobisty do kalendarza, notatek i przypomnień — napędzany przez LLM, bez wysyłania danych osobistych do zewnętrznych dostawców AI w chmurze."
              }
            },
            {
              "label": {
                "en": "Solution:",
                "pl": "Rozwiązanie:"
              },
              "text": {
                "en": "Telegram assistant backed by a self-hosted LLM (Ollama, qwen3-coder) with multi-provider routing. LangGraph multi-agent workflows — a supervisor delegating to specialized agents — handle intent, ChromaDB + sentence-transformers provide semantic long-term memory (RAG), and a Django REST backend with Celery runs async tasks and Google Calendar sync.",
                "pl": "Asystent na Telegramie oparty o self-hostowany LLM (Ollama, qwen3-coder) z routingiem multi-provider. Wieloagentowe przepływy LangGraph — supervisor delegujący do wyspecjalizowanych agentów — obsługują intencje, ChromaDB + sentence-transformers zapewniają semantyczną pamięć długoterminową (RAG), a backend Django REST z Celery obsługuje zadania asynchroniczne i synchronizację z Google Calendar."
              }
            },
            {
              "label": {
                "en": "Stack:",
                "pl": "Stack:"
              },
              "text": "Python · Django · LangGraph · Ollama · ChromaDB · Celery · PostgreSQL · Redis · Docker · Kubernetes"
            },
            {
              "label": {
                "en": "Status:",
                "pl": "Status:"
              },
              "text": {
                "en": "Running on a self-hosted Kubernetes cluster (Rancher, Traefik) deployed via GitHub Actions CI/CD with a self-hosted runner. Agent workflows, semantic memory and calendar sync working; actively expanding agents and RAG.",
                "pl": "Działa na self-hostowanym klastrze Kubernetes (Rancher, Traefik), wdrażany przez CI/CD GitHub Actions z self-hosted runnerem. Przepływy agentowe, pamięć semantyczna i synchronizacja kalendarza działają; aktywnie rozwijam agentów i RAG."
              }
            }
          ]
        },
        {
          "title": "Chessmaster — Chess Opening Trainer",
          "rows": [
            {
              "label": {
                "en": "Problem:",
                "pl": "Problem:"
              },
              "text": {
                "en": "Most opening trainers reward rote memorization. I wanted a tool that teaches you to understand moves, with real engine feedback.",
                "pl": "Większość trenerów otwarć premiuje wkuwanie na pamięć. Chciałem narzędzie, które uczy rozumieć ruchy, z prawdziwą oceną silnika."
              }
            },
            {
              "label": {
                "en": "Solution:",
                "pl": "Rozwiązanie:"
              },
              "text": {
                "en": "Full-stack trainer where Stockfish scores every move (centipawn-loss classification), shows top continuations, idea arrows and an eval bar. Includes gambit training, a test mode with spaced repetition and opening unlocking, PGN game analysis, mistakes replayed as puzzles, themed tactics on the Lichess Puzzle DB (~3M positions), a position editor and JWT-based accounts.",
                "pl": "Full-stackowy trener, w którym Stockfish ocenia każdy ruch (klasyfikacja centipawn-loss), pokazuje najlepsze kontynuacje, strzałki idei i pasek oceny. Zawiera trening gambitów, tryb testowy ze spaced repetition i odblokowywaniem otwarć, analizę partii z PGN, powtórkę błędów jako zagadki, taktykę na bazie Lichess Puzzle DB (~3 mln pozycji), edytor pozycji i konta oparte o JWT."
              }
            },
            {
              "label": {
                "en": "Stack:",
                "pl": "Stack:"
              },
              "text": "Next.js 15 · TypeScript · Tailwind · FastAPI · Stockfish 16 · python-chess · PostgreSQL · Docker · Kubernetes"
            },
            {
              "label": {
                "en": "Live:",
                "pl": "Live:"
              },
              "text": "https://chessmaster.appevil.pl/"
            }
          ]
        },
        {
          "title": "Hardware Random Generator (Teensy)",
          "rows": [
            {
              "label": {
                "en": "Problem:",
                "pl": "Problem:"
              },
              "text": {
                "en": "Software PRNGs are not truly random — insufficient for cryptographic or security-sensitive use cases.",
                "pl": "Programowe generatory liczb pseudolosowych nie są naprawdę losowe — niewystarczające do zastosowań kryptograficznych i bezpieczeństwa."
              }
            },
            {
              "label": {
                "en": "Solution:",
                "pl": "Rozwiązanie:"
              },
              "text": {
                "en": "Microcontroller-based entropy source using hardware noise. Data exposed via USB interface (migrating to Ethernet) and consumed by backend services.",
                "pl": "Źródło entropii oparte na mikrokontrolerze, wykorzystujące szum sprzętowy. Dane udostępniane przez interfejs USB (migracja do Ethernet) i konsumowane przez serwisy backendowe."
              }
            },
            {
              "label": {
                "en": "Stack:",
                "pl": "Stack:"
              },
              "text": "Teensy · C++ · Python · USB/Ethernet"
            },
            {
              "label": {
                "en": "Result:",
                "pl": "Wynik:"
              },
              "text": {
                "en": "True hardware entropy source integrated with software backend.",
                "pl": "Prawdziwe sprzętowe źródło entropii zintegrowane z backendem."
              }
            }
          ]
        }
      ]
    },
    {
      "type": "skills",
      "heading": {
        "en": "Skills",
        "pl": "Umiejętności"
      },
      "groups": [
        {
          "title": {
            "en": "Infrastructure",
            "pl": "Infrastruktura"
          },
          "items": [
            "Kubernetes",
            "Rancher",
            "Docker",
            "Terraform",
            "Ansible",
            "PowerShell"
          ]
        },
        {
          "title": {
            "en": "CI/CD & Automation",
            "pl": "CI/CD i Automatyzacja"
          },
          "items": [
            "GitHub Actions",
            {
              "en": "Bash scripting",
              "pl": "Skrypty Bash"
            },
            "Linux"
          ]
        },
        {
          "title": {
            "en": "Development",
            "pl": "Programowanie"
          },
          "items": [
            "Python",
            "Django",
            "REST API",
            "PostgreSQL"
          ]
        },
        {
          "title": {
            "en": "Networking",
            "pl": "Sieci"
          },
          "items": [
            "DNS, TCP/IP",
            "Reverse Proxy",
            "MQTT"
          ]
        },
        {
          "title": "Embedded / IoT",
          "items": [
            "Raspberry Pi",
            "Teensy",
            "MQTT"
          ]
        },
        {
          "title": {
            "en": "Industrial",
            "pl": "Przemysł"
          },
          "items": [
            "PLC (Allen Bradley)",
            "Siemens TIA Portal",
            "Autodesk Inventor"
          ]
        }
      ]
    },
    {
      "type": "experience",
      "heading": {
        "en": "Experience",
        "pl": "Doświadczenie"
      },
      "items": [
        {
          "role": {
            "en": "DevOps / Platform Engineer",
            "pl": "Inżynier DevOps / Platform"
          },
          "date": {
            "en": "Oct 2024 – Present",
            "pl": "10.2024 – Obecnie"
          },
          "company": "Self-employed / Freelance",
          "bullets": [
            {
              "en": "Currently collaborating with an international company (remote, English-speaking team) — platform testing and validation on Kubernetes",
              "pl": "Obecnie współpracuję z zagraniczną firmą (zdalnie, anglojęzyczny zespół) — testowanie i walidacja platform na Kubernetes"
            },
            {
              "en": "Deployed and configured applications on Kubernetes (Helm, manifests, TLS/ingress)",
              "pl": "Wdrażałem i konfigurowałem aplikacje na Kubernetes (Helm, manifesty, TLS/ingress)"
            },
            {
              "en": "Integrated applications with enterprise authentication (SSO, SAML, OAuth 2.0) and internal platforms via REST APIs",
              "pl": "Integrowałem aplikacje z korporacyjnym uwierzytelnianiem (SSO, SAML, OAuth 2.0) i wewnętrznymi platformami przez REST API"
            },
            {
              "en": "Implemented CI/CD pipelines with GitHub Actions",
              "pl": "Wdrożyłem pipeline'y CI/CD z GitHub Actions"
            }
          ]
        },
        {
          "role": {
            "en": "Test Engineer (Embedded)",
            "pl": "Inżynier Testów (Embedded)"
          },
          "date": {
            "en": "Jul 2023 – Oct 2024",
            "pl": "07.2023 – 10.2024"
          },
          "company": "Garmin",
          "bullets": [
            {
              "en": "Tested infotainment controllers — electronics (PCB) and firmware",
              "pl": "Testowanie sterowników infotainment — elektronika (płytka) i firmware"
            },
            {
              "en": "Owned test stations: repairs, diagnostics and process configuration",
              "pl": "Odpowiedzialność za stacje testowe: naprawy, diagnostyka i ustawienia procesowe"
            }
          ]
        },
        {
          "role": {
            "en": "Industrial Automation Engineer",
            "pl": "Inżynier Automatyki Przemysłowej"
          },
          "date": {
            "en": "Feb 2019 – Jun 2023",
            "pl": "02.2019 – 06.2023"
          },
          "company": "3M",
          "bullets": [
            {
              "en": "Programmed PLCs: Allen Bradley (Studio 5000), Siemens (TIA Portal)",
              "pl": "Programowałem sterowniki PLC: Allen Bradley (Studio 5000), Siemens (TIA Portal)"
            },
            {
              "en": "Mechanical design and documentation in Autodesk Inventor",
              "pl": "Projektowanie mechaniczne i dokumentacja w Autodesk Inventor"
            },
            {
              "en": "Commissioning and troubleshooting of industrial automation systems",
              "pl": "Uruchamianie i diagnostyka przemysłowych systemów automatyki"
            },
            {
              "en": "HMI development and SCADA integration",
              "pl": "Tworzenie interfejsów HMI i integracja SCADA"
            }
          ]
        }
      ]
    },
    {
      "type": "languages",
      "heading": {
        "en": "Languages",
        "pl": "Języki"
      },
      "items": [
        {
          "en": "Polish — Native",
          "pl": "Polski — Ojczysty"
        },
        {
          "en": "English — Professional",
          "pl": "Angielski — Zawodowy"
        }
      ]
    }
  ]
};

// Expose for the page renderer and the visual editor.
if (typeof window !== "undefined") window.CV = CV;
